package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;
import java.util.ArrayList;

import progettoEsame.centropolisportivo.dao.ActivityTypeDAO;
import progettoEsame.centropolisportivo.dao.RoomDAO;

/**
 * ActivityType generated by hbm2java
 */
public class ActivityType{

	private Integer id;
	private CenterManager centerManager;
	private String type;
	
	

	public ActivityType() {
		super();
	}

	public ActivityType(CenterManager centerManager, String type) {
		this.centerManager = centerManager;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}


	public static ArrayList<ActivityType> getAllActivityType() throws SQLException
	{
		return ActivityTypeDAO.getInstance().getAllActivityType();
	}
	
	public static ActivityType findByType(String type) throws SQLException
	{
		return ActivityTypeDAO.getInstance().findByType(type);
	}
	
	public static void insert(ActivityType newActivityType) throws SQLException
	{
		ActivityTypeDAO.getInstance().insert(newActivityType);
	}
}
