package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;

import progettoEsame.centropolisportivo.dao.CsrcDAO;

/**
 * Csrc generated by hbm2java
 */
public class Csrc  {

	private Integer id;
	private Member member;
	private String path;
	private Event event;
	

	public Csrc() {
		super();
	}

	public Csrc(Member member, String path, Event event) {
		this.member = member;
		this.path = path;
		this.event = event;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}
	
	public Event getEvent() {
		return event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public static void insert(Csrc newCsrc)throws SQLException
	{
		CsrcDAO.getInstance().insert(newCsrc);
	}
	
}
