package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Csrc generated by hbm2java
 */
public class Csrc  {

	private Integer id;
	private Member member;
	private String path;
	private Date deadline;

	
	public Csrc() {
		super();
	}

	public Csrc(Member member, String path, Date deadline) {
		this.member = member;
		this.path = path;
		this.deadline = deadline;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

}
