package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;
import java.util.ArrayList;
import progettoEsame.centropolisportivo.dao.EventDAO;


/**
 * Event generated by hbm2java
 */
public class Event  {

	private Integer id;
	private Trainer trainer;
	private String name;
	private java.sql.Date startDate;
	private java.sql.Date finishDate;
	private int cost;
	private String type;
	private boolean free;


	public Event() {
		super();
	}

	public Event(Trainer trainer, String name, java.sql.Date startDate, java.sql.Date finishDate, int cost, String type, boolean free) {
		this.trainer = trainer;
		this.name = name;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.cost = cost;
		this.type = type;
		this.free = free;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Trainer getTrainer() {
		return this.trainer;
	}

	public void setTrainer(Trainer trainer) {
		this.trainer = trainer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public java.sql.Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(java.sql.Date startDate) {
		this.startDate = startDate;
	}

	public java.sql.Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(java.sql.Date finishDate) {
		this.finishDate = finishDate;
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean isFree() {
		return this.free;
	}

	public void setFree(boolean free) {
		this.free = free;
	}
	
	public static void insert(Event newEvent) throws SQLException
	{
		EventDAO.getInstance().insert(newEvent);
	}
	
	public static ArrayList<Event> getAllEvent() throws SQLException
	{
		return EventDAO.getInstance().getAllEvent();
	}
	
	public static ArrayList<Event> getAllRegisteredActivities(String memberEmail) throws SQLException
	{
		return EventDAO.getInstance().getAllRegisteredActivities(memberEmail);
	}
	

	
}
