package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;


/**
 * Event generated by hbm2java
 */
public class Event  {

	private Integer id;
	private Trainer trainer;
	private String name;
	private Date startDate;
	private Date finishDate;
	private int cost;
	private String type;
	private boolean free;


	public Event() {
		super();
	}

	public Event(Trainer trainer, String name, Date startDate, Date finishDate, int cost, String type, boolean free) {
		this.trainer = trainer;
		this.name = name;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.cost = cost;
		this.type = type;
		this.free = free;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Trainer getTrainer() {
		return this.trainer;
	}

	public void setTrainer(Trainer trainer) {
		this.trainer = trainer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean isFree() {
		return this.free;
	}

	public void setFree(boolean free) {
		this.free = free;
	}

	
}
