package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;

import progettoEsame.centropolisportivo.dao.LevelDAO;
import progettoEsame.centropolisportivo.dao.MemberDAO;

/**
 * Level generated by hbm2java
 */
public class Level {

	private Integer id;
	private CenterManager centerManager;
	private String name;
	private String description;


	

	public Level() {
		super();
	}

	public Level(CenterManager centerManager, String name, String description) {
		this.centerManager = centerManager;
		this.name = name;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public static void insert(Level newLevel) throws SQLException
	{
		LevelDAO.getInstance().insert(newLevel);
	}
	
	public static Level findByName(String name)throws SQLException
	{
		return LevelDAO.getInstance().findByName(name);
	}

}
