package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;
import java.util.ArrayList;

import progettoEsame.centropolisportivo.dao.PaymentDAO;

/**
 * Payment generated by hbm2java
 */
public class Payment   {

	private Integer id;
	private Member member;
	private String type;
	private String number;
	private Double amount;
	private int confirmed;
	private Activity activity;
	private CenterManager centerManager;
	private Event event;
	
	
	public Payment() {
		super();
	}


	public Payment(Integer id, Member member, String type, String number, Double amount, int confirmed,
			Activity activity,CenterManager centerManager) {
		super();
		this.id = id;
		this.member = member;
		this.type = type;
		this.number = number;
		this.amount = amount;
		this.confirmed = confirmed;
		this.activity = activity;
	}


	public CenterManager getCenterManager() {
		return centerManager;
	}


	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}


	public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public Member getMember() {
		return member;
	}


	public void setMember(Member member) {
		this.member = member;
	}


	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}


	public String getNumber() {
		return number;
	}


	public void setNumber(String number) {
		this.number = number;
	}


	public Double getAmount() {
		return amount;
	}


	public void setAmount(Double amount) {
		this.amount = amount;
	}


	public int getConfirmed() {
		return confirmed;
	}


	public void setConfirmed(int confirmed) {
		this.confirmed = confirmed;
	}


	public Activity getActivity() {
		return activity;
	}


	public void setActivity(Activity activity) {
		this.activity = activity;
	}


	public Event getEvent() {
		return event;
	}


	public void setEvent(Event event) {
		this.event = event;
	}
	
	public static ArrayList<Payment> getAllUnconfirmedPayment() throws SQLException
	{
		return PaymentDAO.getInstance().getAllUnconfirmedPayment();
	}
	
	public static void insert(Payment newPayment) throws SQLException
	{
		PaymentDAO.getInstance().insert(newPayment);
	}
	
	public static Payment findById(int id) throws SQLException
	{
		return PaymentDAO.getInstance().findById(id);
	}
	
	public static void update(Payment newPayment) throws SQLException
	{
		PaymentDAO.getInstance().update(newPayment);
	}
	
	
	

}