package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

/**
 * Payment generated by hbm2java
 */
public class Payment   {

	private Integer id;
	private Member member;
	private String type;
	private String number;

	
	
	
	public Payment() {
		super();
	}

	public Payment(Member member, String type) {
		this.member = member;
		this.type = type;
	}

	public Payment(Member member, String type, String number) {
		this.member = member;
		this.type = type;
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

}
