package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;
import java.util.Date;

import progettoEsame.centropolisportivo.dao.RegistrationDAO;


/**
 * Registration generated by hbm2java
 */
public class Registration  {

	private Integer id;
	private Activity activity;
	private Event event;
	private Member member;
	private Level level;
	private java.sql.Date deadline;
	private java.sql.Date date;
	private double cost;

	
	
	public Registration() {
		super();
	}

	public Registration(Activity activity, Event event, Member member, Level level, java.sql.Date deadline, java.sql.Date date) {
		this.activity = activity;
		this.event = event;
		this.member = member;
		this.level = level;
		this.deadline = deadline;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}
	

	public Level getLevel() {
		return level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public java.sql.Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(java.sql.Date deadline) {
		this.deadline = deadline;
	}

	public java.sql.Date getDate() {
		return this.date;
	}

	public void setDate(java.sql.Date date) {
		this.date = date;
	}
	
	public double getCost() {
		return cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	public static Registration findById(int id) throws SQLException
	{
		return RegistrationDAO.getInstance().findById(id);
	}
}
