package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;


/**
 * Registration generated by hbm2java
 */
public class Registration  {

	private Integer id;
	private Activity activity;
	private Event event;
	private Member member;
	private Schedule schedule;
	private Date deadline;
	private Date date;

	
	
	public Registration() {
		super();
	}

	public Registration(Activity activity, Event event, Member member, Schedule schedule, Date deadline, Date date) {
		this.activity = activity;
		this.event = event;
		this.member = member;
		this.schedule = schedule;
		this.deadline = deadline;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
}
