package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1




/**
 * Room generated by hbm2java
 */
public class Room {

	private Integer id;
	private CenterManager centerManager;
	private String name;
	private String description;
	private int capability;

	public Room() {
	}

	public Room(CenterManager centerManager, String name, int capability) {
		this.centerManager = centerManager;
		this.name = name;
		this.capability = capability;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getCapability() {
		return this.capability;
	}

	public void setCapability(int capability) {
		this.capability = capability;
	}

}
