package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * TempAlterRegistration generated by hbm2java
 */
public class TempAlterRegistration  {

	private Integer id;
	private CenterManager centerManager;
	private Member member;
	private Registration registration;
	private Date deadline;
	private Date date;
	private boolean confirmed;

	

	public TempAlterRegistration() {
		super();
	}

	public TempAlterRegistration(CenterManager centerManager, Member member, Registration registration, Date deadline,
			Date date, boolean confirmed) {
		this.centerManager = centerManager;
		this.member = member;
		this.registration = registration;
		this.deadline = deadline;
		this.date = date;
		this.confirmed = confirmed;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean isConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(boolean confirmed) {
		this.confirmed = confirmed;
	}

}
