package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * TempAlterRegistration generated by hbm2java
 */
public class TempAlterRegistration  {

	private Integer id;
	private CenterManager centerManager;
	private Member member;
	private Registration registration;
	private int confirmed;
	private Level level;

	

	public TempAlterRegistration() {
		super();
	}

	public TempAlterRegistration(CenterManager centerManager, Member member, Registration registration,int confirmed,Level level) {
		this.centerManager = centerManager;
		this.member = member;
		this.registration = registration;
		this.confirmed = confirmed;
		this.level = level;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}


	public Level getLevel() {
		return level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public int isConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(int confirmed) {
		this.confirmed = confirmed;
	}

}
