package progettoEsame.centropolisportivo.model;
// Generated 26-gen-2017 22.33.09 by Hibernate Tools 5.2.0.CR1

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;

import progettoEsame.centropolisportivo.dao.TempAlterRegistrationDAO;

/**
 * TempAlterRegistration generated by hbm2java
 */
public class TempAlterRegistration  {

	private Integer id;
	private CenterManager centerManager;
	private Member member;
	private Registration registration;
	private int confirmed;
	private Level level;

	

	public TempAlterRegistration() {
		super();
	}

	public TempAlterRegistration(CenterManager centerManager, Member member, Registration registration,int confirmed,Level level) {
		this.centerManager = centerManager;
		this.member = member;
		this.registration = registration;
		this.confirmed = confirmed;
		this.level = level;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CenterManager getCenterManager() {
		return this.centerManager;
	}

	public void setCenterManager(CenterManager centerManager) {
		this.centerManager = centerManager;
	}

	public Member getMember() {
		return this.member;
	}

	public void setMember(Member member) {
		this.member = member;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}


	public Level getLevel() {
		return level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public int isConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(int confirmed) {
		this.confirmed = confirmed;
	}
	
	public static int insert(TempAlterRegistration newTempAlterRegistration)throws SQLException
	{
		return TempAlterRegistrationDAO.getInstance().insert(newTempAlterRegistration);
	}
	
	public static TempAlterRegistration findById(int id)throws SQLException
	{
		return TempAlterRegistrationDAO.getInstance().findById(id);
	}
	
	public static ArrayList<TempAlterRegistration> getAllRequests()throws SQLException
	{
		return TempAlterRegistrationDAO.getInstance().getAllTempAlertRegistrations();
	}
	
	public static void deleteAlterRegistration(Integer id) throws SQLException
	{
		TempAlterRegistrationDAO.getInstance().delete(id);
	}

}
